language: php
php: "7.1"

branches:
  only:
    - source

script:
  - php ./_generator/generate.php

before_deploy:
  - rm -rf _**  # Remove all files and folders with a underscore prefix (generator files)
  - rm .gitignore
  - rm .travis.yml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target-branch: master
  email: frederike.gnampf@gmail.com
  name: SkayoBot
  on:
    branch: source